// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-zwirBZvbOb5gyb3rhgTExQQPCkp9Uo',
    appId: '1:102504064630:android:9e31bc7fbb29bb2d47a157',
    messagingSenderId: '102504064630',
    projectId: 'tabrik-va-tilaklar',
    databaseURL: 'https://tabrik-va-tilaklar-default-rtdb.firebaseio.com',
    storageBucket: 'tabrik-va-tilaklar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1r6BmVHg-wrb9qjQUapDIsot0t6mhS4c',
    appId: '1:102504064630:ios:bb6526b963dc33c147a157',
    messagingSenderId: '102504064630',
    projectId: 'tabrik-va-tilaklar',
    databaseURL: 'https://tabrik-va-tilaklar-default-rtdb.firebaseio.com',
    storageBucket: 'tabrik-va-tilaklar.appspot.com',
    iosBundleId: 'com.uz.m.abbos.tabriklar',
  );

}